version: '3'
services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user1'
      POSTGRES_PASSWORD: 'user1-pass'
  web:
    image: 805641289223.dkr.ecr.ap-northeast-1.amazonaws.com/stock-rolling-app:latest
    entrypoint: ./wait-for-it.sh db:5432
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - chrome
    environment:
      REDIS_URL: redis://redis:6379
      CHROME_URL: chrome://chrome:4444
  nginx:
    image: nginx:1.18
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
      - ./public:/web/public
    depends_on:
      - web
  redis:
      image: "redis:latest"
      command: redis-server --appendonly yes
      ports:
        - "6379:6379"
      volumes:
        - redis:/var/lib/redis/data
  sidekiq:
    image: 805641289223.dkr.ecr.ap-northeast-1.amazonaws.com/stock-rolling-app:latest
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - db
    tty: true
  chrome:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: "2gb"
    tty: true
volumes:
  bundle_data:
  postgres:
  redis:
  sidekiq:
  nginx: