version: '3'
services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user1'
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  app:
    container_name: app
    image: 805641289223.dkr.ecr.ap-northeast-1.amazonaws.com/stock-rolling-app:latest
    volumes:
      - public-data:/StockRollingApp/public
      - tmp-data:/StockRollingApp/tmp
      - log-data:/StockRollingApp/log
      - .env:/StockRollingApp/.env
      - ./rails/master.key:/StockRollingApp/config/master.key
    command: bundle exec puma -C config/puma.rb -e production
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - chrome
    environment:
      REDIS_URL: redis://redis:6379
      CHROME_URL: chrome://chrome:4444
  web:
    container_name: web
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - public-data:/StockRollingApp/public
      - tmp-data:/StockRollingApp/tmp
    ports:
      - "80:80"
    depends_on:
      - app
  redis:
      image: "redis:latest"
      command: redis-server --appendonly yes
      ports:
        - "6379:6379"
      volumes:
        - redis:/var/lib/redis/data
  sidekiq:
    image: 805641289223.dkr.ecr.ap-northeast-1.amazonaws.com/stock-rolling-app:latest
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - .env:/StockRollingApp/.env
      - ./rails/master.key:/StockRollingApp/config/master.key
    depends_on:
      - redis
      - db
    tty: true
  chrome:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: "2gb"
    tty: true
volumes:
  bundle_data:
  postgres:
  redis:
  sidekiq:
  public-data:
  tmp-data:
  log-data: